const mockData = [
  {
    id: 1,
    title: "Harry Potter y la piedra filosofal",
    author: "J.K. Rowling",
    price: 20.99,
    description: "El inicio de la icónica saga del joven mago.",
    image: "/img/hp.jpg",
  },
  {
    id: 2,
    title: "Los juegos del hambre",
    author: "Suzanne Collins",
    price: 18.99,
    description: "Un mundo distópico donde la supervivencia es un espectáculo.",
    image: "/img/jh1.jpg",
  },
  {
    id: 3,
    title: "Los juegos del hambre Sinsajo",
    author: "Suzanne Collins",
    price: 18.99,
    description: "Un mundo distópico donde la supervivencia es un espectáculo.",
    image: "/img/jh2.jpg",
  },
  {
    id: 4,
    title: "Los juegos del hambre En llamas",
    author: "Suzanne Collins",
    price: 18.99,
    description: "Un mundo distópico donde la supervivencia es un espectáculo.",
    image: "/img/jh3.jpg",
  },
  {
    id: 5,
    title: "El código Da Vinci",
    author: "Dan Brown",
    price: 21.50,
    description: "Un thriller lleno de misterio y conspiraciones religiosas.",
    image: "/img/cd.jpg",
  },
  {
    id: 6,
    title: "El señor de los anillos: La comunidad del anillo",
    author: "J.R.R. Tolkien",
    price: 25.00,
    description: "El épico inicio de la lucha contra Sauron.",
    image: "/img/sa.jpg",
  },
  {
    id: 7,
    title: "Crepúsculo",
    author: "Stephenie Meyer",
    price: 15.99,
    description: "Un romance entre vampiros y humanos.",
    image: "/img/cr.jpg",
  },
  {
    id: 8,
    title: "El gran Gatsby",
    author: "F. Scott Fitzgerald",
    price: 19.99,
    description: "La historia de Jay Gatsby y su búsqueda del sueño americano.",
    image: "/img/gg.jpg",
  },
  {
    id: 9,
    title: "It (Eso)",
    author: "Stephen King",
    price: 22.99,
    description: "Una aterradora historia de un payaso que acecha niños.",
    image: "/img/it.jpg",
  },
  {
    id: 10,
    title: "La chica del tren",
    author: "Paula Hawkins",
    price: 17.99,
    description: "Un thriller psicológico sobre el misterio de una desaparición.",
    image: "/img/ct.jpg",
  },
  {
    id: 11,
    title: "La lista de Schindler",
    author: "Thomas Keneally",
    price: 24.99,
    description: "La impactante historia de un hombre que salvó miles de vidas.",
    image: "/img/ls.jpg",
  },
  {
    id: 12,
    title: "Las ventajas de ser invisible",
    author: "Stephen Chbosky",
    price: 14.99,
    description: "Una historia de amistad y crecimiento personal.",
    image: "/img/vi.jpg",
  },
  {
    id: 13,
    title: "La ladrona de libros",
    author: "Markus Zusak",
    price: 16.99,
    description: "La vida de una niña durante la Segunda Guerra Mundial.",
    image: "/img/ll.jpg",
  },
  {
    id: 14,
    title: "Un monstruo viene a verme",
    author: "Patrick Ness",
    price: 19.50,
    description: "Un emotivo relato sobre el duelo y la fantasía.",
    image: "/img/um.jpg",
  },
  {
    id: 15,
    title: "El Hobbit",
    author: "J.R.R. Tolkien",
    price: 23.99,
    description: "La aventura de Bilbo Bolsón hacia la Montaña Solitaria.",
    image: "/img/eh.jpg",
  },
  {
    id: 16,
    title: "Divergente",
    author: "Veronica Roth",
    price: 16.99,
    description: "Una sociedad dividida por facciones y un amor prohibido.",
    image: "/img/di.jpg",
  },
  {
    id: 17,
    title: "Yo antes de ti",
    author: "Jojo Moyes",
    price: 19.99,
    description: "Un romance conmovedor entre dos almas opuestas.",
    image: "/img/ya.jpg",
  },
  {
    id: 18,
    title: "Ready Player One",
    author: "Ernest Cline",
    price: 21.50,
    description: "Una búsqueda épica en un mundo virtual lleno de referencias.",
    image: "/img/rp.jpg",
  },
  {
    id: 19,
    title: "Bajo la misma estrella",
    author: "John Green",
    price: 17.99,
    description: "Una historia de amor entre adolescentes enfrentando la adversidad.",
    image: "/img/me.jpg",
  },
  {
    id: 20,
    title: "El marciano",
    author: "Andy Weir",
    price: 20.99,
    description: "La lucha por la supervivencia de un astronauta atrapado en Marte.",
    image: "/img/em.jpg",
  },
  {
    id: 21,
    title: "La saga de Crepúsculo: Luna Nueva",
    author: "Stephenie Meyer",
    price: 15.99,
    description: "El amor y el desamor entre vampiros y humanos.",
    image: "/img/ln.jpg",
  },
  {
    id: 22,
    title: "La saga Crepúsculo: Amanecer",
    author: "Stephenie Meyer",
    price: 18.99,
    description: "La culminación del romance entre Bella y Edward.",
    image: "/img/am.jpg",
  },
];

export default mockData;
